schema_version: 20180708
name: main-flow
version: 0.0.39
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: com.example.fn.HelloFunction::handleRequest
triggers:
- name: main-flow-trigger
  type: http
  source: /main-flow-trigger
