schema_version: 20180708
name: carre-flow
version: 0.0.55
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: com.example.fn.CarreFunction::handleRequest
triggers:
- name: carre-flow-trigger
  type: http
  source: /carre-flow-trigger
