schema_version: 20180708
name: cube-flow
version: 0.0.4
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: com.example.fn.CubeFunction::handleRequest
triggers:
- name: cube-flow-trigger
  type: http
  source: /cube-flow-trigger
